### ISSUE TITLE
Bug: TypeError in Lite module

### ISSUE THREAD

**Issue by troyraen** [mwvgroup/Pitt-Google-Broker#228]
```
 Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 128, in run
    alert_lite = semantic_compression(alert_dict, schema_map)
  File "/workspace/main.py", line 57, in semantic_compression
    for prv_s in access_prev:
TypeError: 'NoneType' object is not iterable 
```

[Error Reporting](https://console.cloud.google.com/errors/detail/CJugxsjZ2tviiQE;service=ztf-lite;time=P1D?version=&project=ardent-cycling-243415)

**Comment by troyraen** [comment]
Re-opening since #229 did not actually fix this.
